[notebook]
dir = "~/hub/src/mdnotes"

[note]
language = "en"
default-title = "untitled"
filename = "{{slug title}}-{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 6
id-case = "lower"

# General notes go to inbox/
[group.general]
paths = ["inbox"]

[group.general.note]
filename = "{{slug title}}-{{id}}"

# Daily notes go to journal/
[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{format-date now '%a-%b-%d-%Y'}}"

# Stories folder
[group.stories]
paths = ["stories"]

[group.stories.note]
filename = "{{slug title}}-{{id}}"
template = "story.md"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "highlight -O ansi {-1}"

# Aliases for one-command workflow
[alias]
i = "zk new --title $argv inbox"
s = "zk new --title $argv stories"
j = "zk today"
r = "zk new --title $argv reference"
p = "zk edit --sort created- --interactive"
t = "zk edit --interactive --tag $argv"
